// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/http;

listener http:Listener ep0 = new (9090);

@http:ServiceConfig {treatNilableAsOptional: true}
service /pricing on ep0 {
    # Confirm pricing of given flightOffers.
    #
    # + xHTTPMethodOverride - the HTTP method to apply
    # + include - Sub-resources to be included:
    # * **credit-card-fees** to get the credit card fee applied on the booking
    # * **bags** to get extra bag options
    # * **other-services** to get services options
    # * **detailed-fare-rules** to get detailed fare rules options
    # + forceClass - parameter to force the usage of booking class for pricing
    # - **true**, to for pricing with the specified booking class
    # - **false**, to get the best available price
    # + payload - list of criteria to confirm the price of a dedicated flight-offers 
    # + return - returns can be any of following types 
    # http:Ok (Successful Operation)
    # http:BadRequest (code    | title                                 
# ------- | ------------------------------------- 
# 477     | INVALID FORMAT
# 2668    | PARAMETER COMBINATION INVALID/RESTRICTED
# 2781    | INVALID LENGTH
# 4926    | INVALID DATA RECEIVED
# 32171   | MANDATORY DATA MISSING
# )
    # http:DefaultStatusCodeResponse (Unexpected error)
    resource function post pricing(("credit-card-fees"|"bags"|"other-services"|"detailed-fare-rules")[]? include, @http:Payload QuoteAirOffersRequest payload, @http:Header {name: "X-HTTP-Method-Override"} string xHTTPMethodOverride = "GET", boolean forceClass = false) returns QuoteAirOffersResponseOk|Error400BadRequest|Error500Default {
        if payload.data.flightOffers.length() == 0 {
            Error400BadRequest bad = {
                body: {errors: [{status: 400, code: 32171, title: "MANDATORY DATA MISSING", detail: "At least one flight offer is required"}]}
            };
            return bad;
        }
        FlightOffer[] priced = from FlightOffer offer in payload.data.flightOffers
            select {
                'type: "flight-offer",
                id: offer.id,
                'source: "GDS",
                instantTicketingRequired: false,
                nonHomogeneous: false,
                oneWay: false,
                paymentCardRequired: false,
                lastTicketingDate: "2026-12-01",
                numberOfBookableSeats: 9,
                itineraries: [
                    {
                        duration: "PT14H35M",
                        segments: [
                            {
                                id: "1",
                                numberOfStops: 0,
                                blacklistedInEU: false,
                                departure: {iataCode: "SYD", terminal: "1", at: "2026-12-10T19:15:00"},
                                arrival: {iataCode: "SIN", terminal: "1", at: "2026-12-11T00:30:00"},
                                carrierCode: "TR",
                                number: "13",
                                aircraft: {code: "789"},
                                operating: {carrierCode: "TR"},
                                duration: "PT8H15M"
                            }
                        ]
                    }
                ],
                price: {
                    currency: "EUR",
                    total: "632.40",
                    base: "400.00",
                    grandTotal: "632.40",
                    billingCurrency: "EUR",
                    taxes: [{amount: "232.40", code: "SG"}]
                },
                pricingOptions: {fareType: ["PUBLISHED"], includedCheckedBagsOnly: true},
                validatingAirlineCodes: ["TR"],
                travelerPricings: [
                    {
                        travelerId: "1",
                        fareOption: "STANDARD",
                        travelerType: "ADULT",
                        price: {currency: "EUR", total: "632.40", base: "400.00"},
                        fareDetailsBySegment: [
                            {segmentId: "1", cabin: "ECONOMY", fareBasis: "LAUAU", 'class: "L", includedCheckedBags: {quantity: 1}}
                        ]
                    }
                ]
            };
        QuoteAirOffersResponseOk ok = {
            body: {
                data: {'type: "flight-offers-pricing", flightOffers: priced},
                dictionaries: {
                    currencies: {"EUR": "EURO"}
                }
            }
        };
        return ok;
    }
}

// Service-mode response types. `bal openapi --mode client` collapses 4XX/5XX
// to `error` and never emits these, so they are defined here for the mock only.
public type Error400BadRequest record {|
    *http:BadRequest;
    Error400 body;
|};

public type Error500Default record {|
    *http:DefaultStatusCodeResponse;
    Error500 body;
|};

public type QuoteAirOffersResponseOk record {|
    *http:Ok;
    QuoteAirOffersResponse body;
|};

public type Error400 record {
    Issue[] errors;
};

public type Error500 record {
    Issue[] errors;
};
