// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the

import ballerina/http;
import ballerina/os;
import ballerina/test;

final boolean isLiveServer = os:getEnv("IS_LIVE_SERVER") == "true";
final string serviceUrl = isLiveServer ? "https://test.api.amadeus.com/v1/shopping/flight-offers" : "http://localhost:9090/pricing";
final string tokenUrl = isLiveServer ? "https://test.api.amadeus.com/v1/security/oauth2/token" : "http://localhost:9444/oauth2/token";
final string clientId = isLiveServer ? os:getEnv("AMADEUS_CLIENT_ID") : "test_client_id";
final string clientSecret = isLiveServer ? os:getEnv("AMADEUS_CLIENT_SECRET") : "test_client_secret";

// The OAuth2 client-credentials grant fetches a token while the client is initialised, so the client is
// created in a BeforeSuite function, after the mock token endpoint is listening.
Client amadeus = test:mock(Client);

@test:BeforeSuite
function initClient() returns error? {
    amadeus = check new ({
        auth: {tokenUrl, clientId, clientSecret},
        httpVersion: isLiveServer ? http:HTTP_2_0 : http:HTTP_1_1
    }, serviceUrl);
}

final FlightOfferPricingIn pricingInput = {
    'type: "flight-offers-pricing",
    flightOffers: [
        {
            'type: "flight-offer",
            id: "1",
            'source: "GDS",
            itineraries: [
                {
                    segments: [
                        {
                            departure: {iataCode: "SYD", at: "2026-12-10T19:15:00"},
                            arrival: {iataCode: "SIN", at: "2026-12-11T00:30:00"},
                            carrierCode: "TR",
                            number: "13",
                            aircraft: {code: "789"},
                            operating: {carrierCode: "TR"},
                            id: "1"
                        }
                    ]
                }
            ]
        }
    ]
};

@test:Config {groups: ["live_tests", "mock_tests"]}
function testQuoteAirOffers() returns error? {
    QuoteAirOffersResponse response = check amadeus->quoteAirOffers({data: pricingInput});
    test:assertEquals(response.data.'type, "flight-offers-pricing");
    test:assertTrue(response.data.flightOffers.length() > 0);
}

@test:Config {groups: ["live_tests", "mock_tests"]}
function testQuoteAirOffersWithQueries() returns error? {
    QuoteAirOffersResponse response = check amadeus->quoteAirOffers({data: pricingInput}, {}, {include: ["bags"], forceClass: false});
    test:assertTrue(response.data.flightOffers.length() > 0);
}

@test:Config {groups: ["mock_tests"]}
function testQuoteAirOffersWithoutOffers() returns error? {
    if isLiveServer {
        return;
    }
    QuoteAirOffersResponse|error response = amadeus->quoteAirOffers({data: {'type: "flight-offers-pricing", flightOffers: []}});
    test:assertTrue(response is error);
}
