// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/constraint;
import ballerina/http;

# OAuth2 Client Credentials Grant Configs
public type OAuth2ClientCredentialsGrantConfig record {|
    *http:OAuth2ClientCredentialsGrantConfig;
    # Token URL
    string tokenUrl = "https://test.api.amadeus.com/v1/security/oauth2/token";
|};

# traveler type
# age restrictions : CHILD < 12y, HELD_INFANT < 2y, SEATED_INFANT < 2y, SENIOR >=60y
public type TravelerType "ADULT"|"CHILD"|"SENIOR"|"YOUNG"|"HELD_INFANT"|"SEATED_INFANT"|"STUDENT";

public type Dictionaries record {
    AircraftEntry aircraft?;
    LocationEntry locations?;
    CarrierEntry carriers?;
    CurrencyEntry currencies?;
};

public type Issue record {
    # an application-specific error code
    int code?;
    # explanation of the error
    string detail?;
    # an object containing references to the source of the error
    IssueSource 'source?;
    # a short summary of the error
    string title?;
    # the HTTP status code applicable to this error
    int status?;
};

# loyalty program information
public type LoyaltyProgram record {
    # loyalty program airline code
    string programOwner?;
    # loyalty program number
    string id?;
};

# address information
public type Address record {
    # Full city name. Example: Dublin
    @constraint:String {pattern: re `[a-zA-Z -]{1,35}`}
    string cityName?;
    # Full state name
    string stateName?;
    # country code [ISO 3166-1 country code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)
    @constraint:String {pattern: re `[a-zA-Z]{2}`}
    string countryCode?;
    # Example: 74130
    string postalCode?;
    # E.g. BP 220
    string postalBox?;
    # Line 1 = Street address, Line 2 = Apartment, suite, unit, building, floor, etc
    string[] lines?;
};

public type AircraftEntry record {|
    string...;
|};

public type LocationEntry record {|
    LocationValue...;
|};

# a tax
public type Tax record {
    string amount?;
    string code?;
};

public type AdditionalServicesRequest record {
    # Details of chargeable checked bags
    ChargeableCheckedBags chargeableCheckedBags?;
    # DEPRECATED - use the chargeableSeat attribute -  seat number
    @constraint:String {pattern: re `[1-9][0-9]{0,2}[A-Z]?`}
    string chargeableSeatNumber?;
    # Other services to add
    ServiceName[] otherServices?;
    # Details of chargeable seat
    ChargeableSeat chargeableSeat?;
};

public type CurrencyEntry record {|
    string...;
|};

# the information that are found on an ID document
public type Document record {
    # Date after which the document is not valid anymore
    string expiryDate?;
    # The document number (shown on the document) . E.g. QFU514563221J
    string number?;
    # Birth place as indicated on the document
    string birthPlace?;
    # [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) of the nationality appearing on the document
    @constraint:String {pattern: re `[a-zA-Z]{2}`}
    string nationality?;
    # Date at which the document has been issued
    string issuanceDate?;
    # [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) of the country that issued the document
    @constraint:String {pattern: re `[a-zA-Z]{2}`}
    string issuanceCountry?;
    # A more precise information concerning the place where the document has been issued, when available. It may be a country, a state, a city or any other type of location. e.g. New-York
    string issuanceLocation?;
};

# name
public type Name record {
    *BaseName;
    # second last name
    string secondLastName?;
};

# an object containing references to the source of the error
public type IssueSource record {
    # a JSON Pointer [RFC6901] to the associated entity in the request document
    string pointer?;
    # a string indicating which URI query parameter caused the issue
    string 'parameter?;
    # a string indicating an example of the right value
    string example?;
};

# stakeholder definition
public type Stakeholder record {
    # The gender
    StakeholderGender gender?;
    # Advanced Passenger Information - regulatory identity documents - SSR DOCS & DOCO elements
    IdentityDocument[] documents?;
    # name
    Name name?;
    # The date of birth in ISO 8601 format (yyyy-mm-dd)
    string dateOfBirth?;
    # item identifier
    string id?;
};

# checked bag
public type Bags record {
    *BaggageAllowance;
    # Specify if the service is bookable by itinerary  or for all itineraries
    boolean bookableByItinerary?;
    # Id of the traveler concerned by the service
    string[] travelerIds?;
    # elementaryPrice
    ElementaryPrice price?;
    # Type of service
    string name?;
    # Id of the segment concerned by the service
    string[] segmentIds?;
};

public type TermAndCondition record {
    string circumstances?;
    string maxPenaltyAmount?;
    # This defines what type of modification is concerned in this rule
    "REFUND"|"EXCHANGE"|"REVALIDATION"|"REISSUE"|"REBOOK"|"CANCELLATION" category?;
    Description[] descriptions?;
    boolean notApplicable?;
};

public type PricingIncludedResources record {
    # Map of fee applied by credit card brand
    record {|CreditCardFee...;|} credit\-card\-fees?;
    # Map of fee applied by bag option
    record {|Bags...;|} bags?;
    # Map of fee applied by service
    record {|OtherServices...;|} other\-services?;
    # Map of fare rules applied by farebasis
    record {|DetailedFareRules...;|} detailed\-fare\-rules?;
};

public type Itinerary record {
    # duration in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) PnYnMnDTnHnMnS format, e.g. PT2H10M for a duration of 2h10m
    string duration?;
    @constraint:Array {maxLength: 9, minLength: 1}
    Segment[] segments;
};

public type QuoteAirOffersResponse record {
    Issue[] warnings?;
    # priced flight Offers and conditions
    FlightOfferPricingOut data;
    PricingIncludedResources included?;
    Dictionaries dictionaries?;
};

public type LocationValue record {
    # City code associated to the airport
    string cityCode?;
    # Country code of the airport
    string countryCode?;
};

public type FlightOffer record {
    # If true, a payment card is mandatory to book this flight offer
    boolean paymentCardRequired?;
    # Number of seats bookable in a single request. Can not be higher than 9
    @constraint:Number {minValue: 1, maxValue: 9}
    decimal numberOfBookableSeats?;
    # Fare information for each traveler/segment
    @constraint:Array {maxLength: 18, minLength: 1}
    TravelerPricing[] travelerPricings?;
    # If true, inform that a ticketing will be required at booking step
    boolean instantTicketingRequired?;
    # This option ensures that the system will only consider offers with these airlines as validating carrier
    @constraint:Array {maxLength: 9, minLength: 1}
    string[] validatingAirlineCodes?;
    # BOOK step ONLY - If true, allows to book a PNR without pricing. Only for the source "GDS"
    boolean disablePricing?;
    # source of the flight offer
    FlightOfferSource 'source?;
    # the resource name
    string 'type;
    # If true, the flight offer can be combined with other oneWays flight-offers to complete the whole journey (one-Way combinable feature)
    boolean oneWay?;
    # price information
    ExtendedPrice price?;
    PricingOptions pricingOptions?;
    # If true, upon completion of the booking, this pricing solution is expected to yield multiple records (a record contains booking information confirmed and stored, typically a Passenger Name Record (PNR), in the provider GDS or system)
    boolean nonHomogeneous?;
    @constraint:Array {maxLength: 250, minLength: 1}
    Itinerary[] itineraries?;
    # If booked on the same day as the search (with respect to timezone), this flight offer is guaranteed to be thereafter valid for ticketing until this date (included). Unspecified when it does not make sense for this flight offer (e.g. no control over ticketing once booked). YYYY-MM-DD format, e.g. 2019-06-07
    string lastTicketingDate?;
    # Id of the flight offer
    string id;
    # If booked on the same day as the search (with respect to timezone), this flight offer is guaranteed to be thereafter valid for ticketing until this date/time (included). Unspecified when it does not make sense for this flight offer (e.g. no control over ticketing once booked). Information only this attribute is not used in input of pricing request. Local date and time in YYYY-MM-ddThh:mm:ss format, e.g. 2017-02-10T20:40:00
    string lastTicketingDateTime?;
};

# Provides a set of configurations for controlling the behaviours when communicating with a remote HTTP endpoint.
@display {label: "Connection Config"}
public type ConnectionConfig record {|
    # Configurations related to client authentication
    OAuth2ClientCredentialsGrantConfig auth;
    # The HTTP version understood by the client
    http:HttpVersion httpVersion = http:HTTP_2_0;
    # Configurations related to HTTP/1.x protocol
    http:ClientHttp1Settings http1Settings = {};
    # Configurations related to HTTP/2 protocol
    http:ClientHttp2Settings http2Settings = {};
    # The maximum time to wait (in seconds) for a response before closing the connection
    decimal timeout = 30;
    # The choice of setting `forwarded`/`x-forwarded` header
    string forwarded = "disable";
    # Configurations associated with Redirection
    http:FollowRedirects followRedirects?;
    # Configurations associated with request pooling
    http:PoolConfiguration poolConfig?;
    # HTTP caching related configurations
    http:CacheConfig cache = {};
    # Specifies the way of handling compression (`accept-encoding`) header
    http:Compression compression = http:COMPRESSION_AUTO;
    # Configurations associated with the behaviour of the Circuit Breaker
    http:CircuitBreakerConfig circuitBreaker?;
    # Configurations associated with retrying
    http:RetryConfig retryConfig?;
    # Configurations associated with cookies
    http:CookieConfig cookieConfig?;
    # Configurations associated with inbound response size limits
    http:ResponseLimitConfigs responseLimits = {};
    # SSL/TLS-related options
    http:ClientSecureSocket secureSocket?;
    # Proxy server related options
    http:ProxyConfig proxy?;
    # Provides settings related to client socket configuration
    http:ClientSocketConfig socketConfig = {};
    # Enables the inbound payload validation functionality which provided by the constraint package. Enabled by default
    boolean validation = true;
    # Enables relaxed data binding on the client side. When enabled, `nil` values are treated as optional, 
    # and absent fields are handled as `nilable` types. Enabled by default.
    boolean laxDataBinding = true;
|};

# Details of chargeable seat
public type ChargeableSeat record {
    # seat number
    @constraint:String {pattern: re `[1-9][0-9]{0,2}[A-Z]?`}
    string number?;
    # Id of the chargeable seat
    string id?;
};

public type DetailedFareRules record {
    string fareBasis?;
    TermAndCondition fareNotes?;
    # Id of the segment concerned by the fare rule
    string segmentId?;
    string name?;
};

# quality of service offered in the cabin where the seat is located in this flight. Economy, premium economy, business or first class
public type TravelClass "ECONOMY"|"PREMIUM_ECONOMY"|"BUSINESS"|"FIRST";

# departure or arrival information
public type FlightEndPoint record {
    *OriginalFlightEndPoint;
    # local date and time in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) YYYY-MM-ddThh:mm:ss format, e.g. 2017-02-10T20:40:00
    string at?;
};

# documents of the traveler
public type IdentityDocument record {
    *Document;
    # [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) of the country where the document is valid
    string validityCountry?;
    # the nature/type of the document
    DocumentType documentType?;
    # [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) of the country of birth
    string birthCountry?;
    # boolean to specify if the traveler is the holder of the document
    boolean holder?;
};

# description of the name of a physical person
public type BaseName record {
    # First name
    string firstName?;
    # Last name
    string lastName?;
    # Middle name(s), for example "Lee" in "John Lee Smith"
    string middleName?;
};

# type of discount applied
public type DiscountTravelerType "SPANISH_CITIZEN"|"EUROPEAN_CITIZEN"|"GOVERNMENT_WORKER"|"MILITARY"|"MINOR_WITHOUT_ID";

# departure or arrival information
public type OriginalFlightEndPoint record {
    # [IATA airline codes](http://www.iata.org/publications/Pages/code-search.aspx)
    string iataCode?;
    # terminal name / number
    string terminal?;
};

# details of stops for direct or change of gauge flights
public type OriginalFlightStop record {
    # stop duration in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) PnYnMnDTnHnMnS format, e.g. PT2H10M
    string duration?;
    # [IATA airline codes](http://www.iata.org/publications/Pages/code-search.aspx)
    string iataCode?;
};

# Fare details of the segment
public type FareDetailsBySegment record {
    # True if the corresponding booking class is in an allotment
    boolean isAllotment?;
    AdditionalServicesRequest additionalServices?;
    # baggageAllowance
    BaggageAllowance includedCheckedBags?;
    # Fare basis specifying the rules of a fare. Usually, though not always, is composed of the booking class code followed by a set of letters and digits representing other characteristics of the ticket, such as refundability, minimum stay requirements, discounts or special promotional elements
    string fareBasis?;
    # Id of the segment
    string segmentId;
    # quality of service offered in the cabin where the seat is located in this flight. Economy, premium economy, business or first class
    TravelClass cabin?;
    # The code of the booking class, a.k.a. class of service or Reservations/Booking Designator (RBD)
    @constraint:String {pattern: re `[A-Z]{1}`}
    string 'class?;
    # slice and Dice indicator, such as Local Availability, Sub OnD(Origin and Destination) 1 Availability and Sub OnD 2 Availability
    SliceDiceIndicator sliceDiceIndicator?;
    # The name of the Fare Family corresponding to the fares. Only for the GDS provider and if the airline has fare families filled
    string brandedFare?;
    AllotmentDetails allotmentDetails?;
};

public type Payment record {
    # Id of the flightOffers to pay
    @constraint:Array {maxLength: 6, minLength: 1}
    string[] flightOfferIds?;
    # The first 6 digits of the credit card
    int binNumber?;
    # credit card brand
    PaymentBrand brand?;
};

public type Price record {
    # Total amount paid by the user
    string total?;
    # List of applicable fees
    Fee[] fees?;
    Tax[] taxes?;
    string currency?;
    # The amount of taxes which are refundable
    string refundableTaxes?;
    # Amount without taxes
    string base?;
};

# type of service
public type ServiceName "PRIORITY_BOARDING"|"AIRPORT_CHECKIN";

# type of discount applied
public type DiscountType "SPANISH_RESIDENT"|"AIR_FRANCE_DOMESTIC"|"AIR_FRANCE_COMBINED"|"AIR_FRANCE_METROPOLITAN";

# Details of chargeable checked bags
public type ChargeableCheckedBags record {
    *BaggageAllowance;
    # Id of the chargeable bag
    string id?;
};

public type OtherServices record {
    # Specify if the service is bookable by itinerary or for all itineraries
    boolean bookableByItinerary?;
    # Id of the traveler concerned by the service
    string[] travelerIds?;
    # elementaryPrice
    ElementaryPrice price?;
    # Specify if the service is bookable by traveler or for all travelers
    boolean bookableByTraveler?;
    # type of service
    ServiceName name?;
    # Id of the segment concerned by the service
    string[] segmentIds?;
};

# source of the flight offer
public type FlightOfferSource "GDS";

# details of stops for direct or change of gauge flights
public type FlightStop record {
    *OriginalFlightStop;
    # departure from the stop in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) YYYY-MM-ddThh:mm:ss format, e.g. 2017-02-10T20:40:00
    string departureAt?;
    # arrival at the stop in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) YYYY-MM-ddThh:mm:ss format, e.g. 2017-02-10T20:40:00
    string arrivalAt?;
};

# emergency contact number
public type EmergencyContact record {
    # Phone number. Composed of digits only. The number of digits depends on the country
    @constraint:String {pattern: re `[0-9]{1,15}`}
    string number?;
    # Country code of the country (ISO3166-1). E.g. "US" for the United States
    @constraint:String {pattern: re `[A-Z]{2}`}
    string countryCode?;
    # Adressee name (e.g. in case of emergency purpose it corresponds to name of the person to be contacted)
    @constraint:String {pattern: re `[a-zA-Z -]`}
    string addresseeName?;
    # additional details
    string text?;
};

# traveler discount
public type Discount record {
    # city of residence
    string cityName?;
    # type of discount applied
    DiscountTravelerType travelerType?;
    # resident certificate number
    @constraint:String {pattern: re `[0-9A-Z][0-9]{0,12}[A-Z]`}
    string certificateNumber?;
    # type of discount applied
    DiscountType subType?;
    # resident card number
    @constraint:String {pattern: re `[0-9A-Z][0-9]{0,12}[A-Z]`}
    string cardNumber?;
};

public type Description record {
    string descriptionType?;
    string text?;
};

# type of fee
public type FeeType "TICKETING"|"FORM_OF_PAYMENT"|"SUPPLIER";

# the purpose for which this contact is to be used
public type ContactPurpose "STANDARD"|"INVOICE"|"STANDARD_WITHOUT_TRANSMISSION";

public type AdditionalService record {
    string amount?;
    # additional service type
    AdditionalServiceType 'type?;
};

public type AllotmentDetails record {
    # The tour name agreed for this specific allotment
    string tourName?;
    # The tour reference agreed for this specific allotment
    string tourReference?;
};

public type PricingOptions record {
    # If true, returns the flight-offers with included checked bags only
    boolean includedCheckedBagsOnly?;
    # If true, returns the flight-offers with no restriction fares only
    boolean noRestrictionFare?;
    # If true, returns the flight-offers with no penalty fares only
    boolean noPenaltyFare?;
    # type of fare of the flight-offer
    PricingOptionsFareType fareType?;
    # If true, returns the flight-offers with refundable fares only
    boolean refundableFare?;
};

public type Co2Emission record {
    # Weight of Co2 emitted for the concerned segment
    int weight?;
    # quality of service offered in the cabin where the seat is located in this flight. Economy, premium economy, business or first class
    TravelClass cabin?;
    # Code to qualify unit as pounds or kilos
    string weightUnit?;
};

public type Segment record {
    # Number of stops
    int numberOfStops?;
    # When the flight has a marketing or/and operating airline that is identified as blacklisted by the European Commission. 
    # 
    # To improve travel safety, the European Commission regularly updates the list of the banned carriers from operating in Europe. It allows any Travel Agency located in the European Union to easily identify and hide any travel recommendation based on some unsafe airlines. 
    # The [list of the banned airlines](https://ec.europa.eu/transport/sites/transport/files/air-safety-list_en.pdf) is published in the Official Journal of the European Union, where they are included as annexes A and B to the Commission Regulation. The blacklist of an airline can concern all its flights or some specific aircraft types pertaining to the airline   
    boolean blacklistedInEU?;
    # Id of the segment
    string id?;
    # Co2 informations
    Co2Emission[] co2Emissions?;
    *FlightSegment;
};

# priced flight Offers and conditions
public type FlightOfferPricingOut record {
    # list of flight offer to price
    @constraint:Array {maxLength: 6, minLength: 1}
    FlightOffer[] flightOffers;
    # pricing condition at booking level
    BookingRequirements bookingRequirements?;
    # the resource name
    string 'type;
};

# defining a flight segment; including both operating and marketing details when applicable
public type FlightSegment record {
    # stop duration in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) PnYnMnDTnHnMnS format, e.g. PT2H10M
    string duration?;
    # the flight number as assigned by the carrier
    @constraint:String {maxLength: 4, minLength: 1}
    string number?;
    # departure or arrival information
    FlightEndPoint arrival?;
    # providing the airline / carrier code
    @constraint:String {maxLength: 2, minLength: 1}
    string carrierCode?;
    # information related to the aircraft
    AircraftEquipment aircraft?;
    # departure or arrival information
    FlightEndPoint departure?;
    # information about the operating flight
    OperatingFlight operating?;
    # information regarding the different stops composing the flight segment. E.g. technical stop, change of gauge..
    FlightStop[] stops?;
};

# credit card brand
public type PaymentBrand "VISA"|"AMERICAN_EXPRESS"|"MASTERCARD"|"VISA_ELECTRON"|"VISA_DEBIT"|"MASTERCARD_DEBIT"|"MAESTRO"|"DINERS"|"MASTERCARD_IXARIS"|"VISA_IXARIS"|"MASTERCARD_AIRPLUS"|"UATP_AIRPLUS";

# price information
public type ExtendedPrice record {
    AdditionalService[] additionalServices?;
    # BOOK step ONLY - The price margin percentage (plus or minus) that the booking can tolerate. When set to 0, then no price magin is tolerated
    string margin?;
    # Total amount paid by the user (including fees and selected additional services)
    string grandTotal?;
    # Currency of the payment. It may be different than the requested currency
    string billingCurrency?;
    *Price;
};

public type QuoteAirOffersRequest record {
    # input parameter to price flight offers element
    FlightOfferPricingIn data;
};

# phone information
public type Phone record {
    # Type of the device (Landline, Mobile or Fax)
    PhoneDeviceType deviceType?;
    # Phone number. Composed of digits only. The number of digits depends on the country
    @constraint:String {pattern: re `[0-9]{1,15}`}
    string number?;
    # Country calling code of the phone number, as defined by the International Communication Union. Examples - "1" for US, "371" for Latvia
    @constraint:String {pattern: re `[0-9+]{2,5}`}
    string countryCallingCode?;
};

# elementaryPrice
public type ElementaryPrice record {
    # Amount of the fare. could be alpha numeric. Ex- 500.20 or 514.13A, 'A'signifies additional collection
    string amount?;
    # Currency type of the fare
    string currencyCode?;
};

# represents a contact
public type ContactDictionary record {
    # address information
    Address address?;
    # the purpose for which this contact is to be used
    ContactPurpose purpose?;
    # name
    Name addresseeName?;
    # the preferred language of communication with this Contact
    string language?;
};

public type CreditCardFee record {
    string amount?;
    string currency?;
    # Id of the flightOffer concerned by the credit card fee
    string flightOfferId?;
    # credit card brand
    PaymentBrand brand?;
};

# information related to the aircraft
public type AircraftEquipment record {
    # IATA aircraft code (http://www.flugzeuginfo.net/table_accodes_iata_en.php)
    @constraint:String {pattern: re `[a-zA-Z0-9]{3}`}
    string code?;
};

# The gender
public type StakeholderGender "MALE"|"FEMALE";

public type PassengerConditions record {
    # If true, the address is required for the concerned traveler for the creation of the flight-order
    boolean residenceRequired?;
    # If true, the isuance city of the document is required for the concerned traveler for the creation of the flight-order
    boolean documentIssuanceCityRequired?;
    # If true, the date of bitrth is required for the concerned traveler for the creation of the flight-order
    boolean dateOfBirthRequired?;
    # If true, a document is required for the concerned traveler for the creation of the flight-order
    boolean documentRequired?;
    # If true, the Air France discount is required for the concerned traveler for the creation of the flight-order
    boolean airFranceDiscountRequired?;
    # If true, the gender is required for the concerned traveler for the creation of the flight-order
    boolean genderRequired?;
    # If true, the Spanish resident discount is required for the concerned traveler for the creation of the flight-order
    boolean spanishResidentDiscountRequired?;
    # If true, the redress is required if any for the concerned traveler for the creation of the flight-order
    boolean redressRequiredIfAny?;
    # Id of the traveler
    string travelerId?;
};

# input parameter to price flight offers element
public type FlightOfferPricingIn record {
    # list of flight offer to price
    @constraint:Array {maxLength: 6, minLength: 1}
    FlightOffer[] flightOffers;
    # payment information for retrieve eventual credit card fees
    @constraint:Array {maxLength: 6}
    Payment[] payments?;
    # the resource name
    string 'type;
    # list of travelers
    @constraint:Array {maxLength: 18}
    Traveler[] travelers?;
};

# a fee
public type Fee record {
    string amount?;
    # type of fee
    FeeType 'type?;
};

# pricing condition at booking level
public type BookingRequirements record {
    # If true, an email address is required for the creation of the flight-order
    boolean emailAddressRequired?;
    # If true, an invoice address is required for the creation of the flight-order
    boolean invoiceAddressRequired?;
    # If true, a mobile phone number is required for the creation of the flight-order
    boolean mobilePhoneNumberRequired?;
    # If true, a postal address is required for the creation of the flight-order
    boolean mailingAddressRequired?;
    # If true, a postal code is required for the creation of the flight-order
    boolean postalCodeRequired?;
    # If true, the phone country code (e.g. '33') associated for each phone number is required for the creation of the flight-order
    boolean phoneCountryCodeRequired?;
    # traveler pricing condition
    PassengerConditions[] travelerRequirements?;
    # If true, a phone number is required for the creation of the flight-order
    boolean phoneNumberRequired?;
};

public type TravelerPricing record {
    # traveler type
    # age restrictions : CHILD < 12y, HELD_INFANT < 2y, SEATED_INFANT < 2y, SENIOR >=60y
    TravelerType travelerType;
    Price price?;
    # if type="HELD_INFANT", corresponds to the adult traveler's id who will share the seat
    string associatedAdultId?;
    # option specifying a group of fares, which may be valid under certain conditons
    # Can be used to specify special fare discount for a passenger
    TravelerPricingFareOption fareOption;
    @constraint:Array {maxLength: 18, minLength: 1}
    FareDetailsBySegment[] fareDetailsBySegment;
    # Id of the traveler
    string travelerId;
};

# the nature/type of the document
public type DocumentType "VISA"|"PASSPORT"|"IDENTITY_CARD"|"KNOWN_TRAVELER"|"REDRESS";

# slice and Dice indicator, such as Local Availability, Sub OnD(Origin and Destination) 1 Availability and Sub OnD 2 Availability
public type SliceDiceIndicator "LOCAL_AVAILABILITY"|"SUB_OD_AVAILABILITY_1"|"SUB_OD_AVAILABILITY_2";

# type of fare of the flight-offer
public type PricingOptionsFareType ("PUBLISHED")[];

# contact information
public type Contact record {
    *ContactDictionary;
    # Email address (e.g. john@smith.com)
    string emailAddress?;
    # Name of the company
    string companyName?;
    # Phone numbers
    Phone[] phones?;
};

# Type of the device (Landline, Mobile or Fax)
public type PhoneDeviceType "MOBILE"|"LANDLINE"|"FAX";

# information about the operating flight
public type OperatingFlight record {
    # providing the airline / carrier code
    @constraint:String {maxLength: 2, minLength: 1}
    string carrierCode?;
};

# additional service type
public type AdditionalServiceType "CHECKED_BAGS"|"MEALS"|"SEATS"|"OTHER_SERVICES";

public type CarrierEntry record {|
    string...;
|};

# option specifying a group of fares, which may be valid under certain conditons
# Can be used to specify special fare discount for a passenger
public type TravelerPricingFareOption "STANDARD"|"INCLUSIVE_TOUR"|"SPANISH_MELILLA_RESIDENT"|"SPANISH_CEUTA_RESIDENT"|"SPANISH_CANARY_RESIDENT"|"SPANISH_BALEARIC_RESIDENT"|"AIR_FRANCE_METROPOLITAN_DISCOUNT_PASS"|"AIR_FRANCE_DOM_DISCOUNT_PASS"|"AIR_FRANCE_COMBINED_DISCOUNT_PASS"|"AIR_FRANCE_FAMILY"|"ADULT_WITH_COMPANION"|"COMPANION";

# Represents the Headers record for the operation: quoteAirOffers
public type QuoteAirOffersHeaders record {
    # the HTTP method to apply
    @http:Header {name: "X-HTTP-Method-Override"}
    string xHTTPMethodOverride = "GET";
};

# the traveler of the trip
public type Traveler record {
    *Stakeholder;
    # emergency contact number
    EmergencyContact emergencyContact?;
    # list of loyalty program followed by the traveler
    LoyaltyProgram[] loyaltyPrograms?;
    # contact information
    Contact contact?;
    # list of element that allow a discount
    Discount[] discountEligibility?;
};

# baggageAllowance
public type BaggageAllowance record {
    # Total number of units
    int quantity?;
    # Weight of the baggage allowance
    int weight?;
    # Code to qualify unit as pounds or kilos
    string weightUnit?;
};

# Represents the Queries record for the operation: quoteAirOffers
public type QuoteAirOffersQueries record {
    # Sub-resources to be included:
    #  * **credit-card-fees** to get the credit card fee applied on the booking
    #  * **bags** to get extra bag options
    #  * **other-services** to get services options
    #  * **detailed-fare-rules** to get detailed fare rules options
    ("credit-card-fees"|"bags"|"other-services"|"detailed-fare-rules")[] include?;
    # parameter to force the usage of booking class for pricing
    # - **true**, to for pricing with the specified booking class
    # - **false**, to get the best available price
    boolean forceClass = false;
};
